### ISSUE TITLE
ordnance survey buildings

### ISSUE THREAD

**Issue by buildvoc10** [rebeccasc/BIMtoOSM#8]
Hello have you worked with geojson from ordnance survey datasets to create indoor walls and floors?
see https://buildingshistory.co.uk/storage/osgb1000015671624.geojson 
![image](https://user-images.githubusercontent.com/76884997/233450408-d9808041-42b2-45e1-812d-d9297e3310dd.png)
would like to add internal walls and floors to existing polygons exported from https://buildingshistory.co.uk/#17.91/51.367843/-2.202508

**Comment by rebeccasc** [comment]
We do not work with geojson data. In BIM2OSM we only consider the transformation from Building Information Modeling (BIM) data to OpenStreetMap (OSM) data. Handling geojson data is not supported by this project.
If you want to merge geojson data with OSM data you might be able to do this with the OSM editor [JOSM](https://josm.openstreetmap.de/) using the JOSM plugin [GeoJSON](https://wiki.openstreetmap.org/wiki/JOSM/Plugins/GeoJSON).

**Comment by buildvoc10** [comment]
Hi thanks for comments, ok do you know a script to transform geojson to ifc?

**Comment by rebeccasc** [comment]
No sorry, I don't know such a tool.
